force-app/main/default/objects/Account/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <description>Hold the Hotel Picture.</description>
    <label>Picture</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>Define Hotel Account.</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/Room_Reservation__c/Room_Reservation__c.object-meta.xml
<CustomObject>
    <label>Room Reservation</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Room Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room_Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>The Contact this reservation is associated with.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Room Reservations</relationshipLabel>
    <relationshipName>Room_Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room_Reservation__c/fields/Number_Of_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Rooms__c</fullName>
    <description>The number of rooms needed for this reservation.</description>
    <label>Number Of Rooms</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room_Reservation__c/fields/Reservation_Date__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Date__c</fullName>
    <description>The Date for the Room Reservation.</description>
    <label>Reservation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Room_Reservation__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <description>The Room Type this reservation is associated with.</description>
    <label>Room Type</label>
    <referenceTo>Room_Type__c</referenceTo>
    <relationshipLabel>Room Reservations</relationshipLabel>
    <relationshipName>Room_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room_Type__c/Room_Type__c.object-meta.xml
<CustomObject>
    <label>Room Type</label>
    <nameField>
        <label>Room Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room_Type__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>The Hotel associated to this Room Type.</description>
    <label>Hotel</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Room Types</relationshipLabel>
    <relationshipName>Room_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room_Type__c/fields/Number_Of_Available_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Available_Rooms__c</fullName>
    <description>The number of rooms available for this Room Type.</description>
    <label>Number Of Available Rooms</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController {
    static String HotelRecordTypeId = getHotelRecordTypeId();

    @AuraEnabled(cacheable=true)
    public static String getHotelRecordTypeId() {
        return [
            SELECT id 
            FROM RecordType 
            WHERE Name ='Hotel'
        ].Id;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getHotels() {
        return [
            SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry
            FROM Account
            WHERE RecordTypeId = :HotelRecordTypeId
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContacts() {
        return [
            SELECT Id, Name, Email
            FROM Contact
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Room_Type__c> getRoomTypes(String hotelId) {
        return [
            SELECT Id, Name
            FROM Room_Type__c
            WHERE Hotel__c = :hotelId
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getAvailableRooms(String roomTypeId, Date bookDate) {
        List<Room_Type__c> totalRooms = [
            SELECT Number_Of_Available_Rooms__c
            FROM Room_Type__c
            WHERE Id = :roomTypeId
            WITH SECURITY_ENFORCED
        ];

        Decimal bookedRooms = (Decimal) [
            SELECT SUM(Number_Of_Rooms__c) sumBookedRooms
            FROM Room_Reservation__c
            WHERE Room_Type__c = :roomTypeId 
            AND Reservation_Date__c = :bookDate
            WITH SECURITY_ENFORCED
        ][0].get('sumBookedRooms');

        if(bookedRooms == null){
            bookedRooms = 0;
        }
        return (Integer)(totalRooms[0].Number_Of_Available_Rooms__c) - (Integer)(bookedRooms);
    }

    @AuraEnabled(cacheable=true)
    public static Integer getNumOfReservations(String contactId, Date bookDate) {
        Decimal reservations = (Decimal) [
            SELECT COUNT(Id) countReservations
            FROM Room_Reservation__c
            WHERE Contact__c = :contactId 
            AND Reservation_Date__c = :bookDate
            WITH SECURITY_ENFORCED
        ][0].get('countReservations');

        return (Integer)(reservations);
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> searchHotels(String hotelName) {
        return [
            SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Picture__c
            FROM Account
            WHERE RecordTypeId = :HotelRecordTypeId
            AND Name LIKE :'%' + hotelName + '%'
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }
}